### ISSUE TITLE
CSS bug language switch button

### ISSUE THREAD

**Issue by marceloboeira** [feedcast/hurley#11]
@marvin52 CC

<img width="252" alt="screen shot 2017-08-22 at 17 03 02" src="https://user-images.githubusercontent.com/1898225/29572217-e7e0ba06-875b-11e7-82dc-ba09a4ccb0cc.png">

**Comment by marvin52** [comment]
Let me guess which browser

**Comment by marceloboeira** [comment]
the greatest!
