### ISSUE TITLE
Bugtracker/Rollbar 

### ISSUE THREAD

**Issue by marceloboeira** [feedcast/hurley#18]
@marvin52 is there anything like rollbar or even rollbar for front-end? It would be amazing to have those issues documented. If so, please, let us use the same account as the backend to centralize it.

**Comment by marvin52** [comment]
Yes, i think that rollbar have an option for front end but tracking. https://rollbar.com/docs/notifier/rollbar.js/

**Comment by marceloboeira** [comment]
@marvin52 awesome, butt tracking.

**Comment by marvin52** [comment]
It would be like facial recognition, but of the butt. I think we can change the social contract of the feedcast, we found our mine of gold.

**Comment by marceloboeira** [comment]
What if the screen would become a mirror when the user is looking at the camera?

**Comment by marvin52** [comment]
Now I can only imagine people putting puppy faces on their butts.
