### ISSUE TITLE
Style: Remove content borders on desktop

### ISSUE THREAD

**Issue by marceloboeira** [feedcast/hurley#25]
# FROM

<img width="1440" alt="screen shot 2017-09-14 at 15 16 30" src="https://user-images.githubusercontent.com/1898225/30431978-8b3dd394-9960-11e7-805e-9e6403c5b030.png">

# TO
<img width="1428" alt="screen shot 2017-09-14 at 15 16 13" src="https://user-images.githubusercontent.com/1898225/30431977-8b3c049c-9960-11e7-9281-14d02abe6d08.png">

**Comment by cristianoliveira** [comment]
Changed it here a44ef0ce370d5bf3258851866c941901374418d5

You can take a look on beta:
http://beta.feedcast.dev/channels

**Comment by marceloboeira** [comment]
👍

**Comment by marceloboeira** [comment]
<img width="1271" alt="screen shot 2017-09-14 at 21 12 12" src="https://user-images.githubusercontent.com/1898225/30450766-35b1a3ec-9992-11e7-8918-30dcdb3db569.png">
<img width="913" alt="screen shot 2017-09-14 at 21 16 20" src="https://user-images.githubusercontent.com/1898225/30450767-35b38450-9992-11e7-8819-4383f439cdaf.png">

**Comment by cristianoliveira** [comment]
Fixed adding some margin among the cards:
c9557739f2fb7163066f047ef0aeb60d8a4f8097

**Comment by cristianoliveira** [comment]
Is it still a issue?

**Comment by marceloboeira** [comment]
I checked beta now,  seems okay.

**Comment by cristianoliveira** [comment]
I rest my case
