### ISSUE TITLE
Demo or screenshot?

### ISSUE THREAD

**Issue by onny** [feedcast/hurley#35]
Hey,
it looks like your demo page is down or something else is up there.
Do you have a demo or screenshot for this web app?

Best regards,
Jonas

**Comment by marceloboeira** [comment]
We’ve used to, but I don’t think it’s available anymore ... @cristianoliveira  @marvin52

**Comment by cristianoliveira** [comment]
I have to check, but I'm quite sure it got lost in our Slack :(
